security:
  jwt:
    secret: ${JWT_SECRET:UnsafeSecret}

media:
  storage-dir: ${MEDIA_STORAGE_DIR:./media}

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

docs:
  api-url: ${DOCS_API_URL:/}