services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - products
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/ssl:/etc/ssl
  products:
    image: ghcr.io/merpw/lets-play:${REVISION-main}
    build:
      args:
        - SERVICE_NAME=products
    environment:
      - MONGO_HOST=db
    depends_on:
      - db
  db:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - lets-play-db:/data/db
volumes:
  lets-play-db:

