services:
  nginx:
    image: ghcr.io/merpw/lets-play-nginx:${REVISION-main}
    platform: linux/amd64
    build:
      context: nginx
    environment:
      - SERVER_NAME=${SERVER_NAME-localhost}
      - SSL_CERT=${SSL_CERT}
      - SSL_KEY=${SSL_KEY}
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - users
      - products
      - media
      - frontend
      - swagger-ui
  users:
    image: ghcr.io/merpw/lets-play-users-service:${REVISION-main}
    platform: linux/amd64
    build:
      context: backend
      args:
        - SERVICE_NAME=users
    environment:
      - MONGO_HOST=db
      - DOCS_API_URL=/api
      - JWT_SECRET=${JWT_SECRET}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    depends_on:
      - db
  products:
    image: ghcr.io/merpw/lets-play-products-service:${REVISION-main}
    platform: linux/amd64
    build:
      context: backend
      args:
        - SERVICE_NAME=products
    environment:
      - MONGO_HOST=db
      - DOCS_API_URL=/api
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - db
  media:
    image: ghcr.io/merpw/lets-play-media-service:${REVISION-main}
    platform: linux/amd64
    build:
      context: backend
      args:
        - SERVICE_NAME=media
    environment:
      - MEDIA_STORAGE_DIR=/app/media
      - DOCS_API_URL=/api
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - lets-play-media:/app/media
  orders:
    image: ghcr.io/merpw/lets-play-orders-service:${REVISION-main}
    build:
      context: backend
      args:
        - SERVICE_NAME=orders
    environment:
      - MONGO_HOST=db
      - DOCS_API_URL=/api
    depends_on:
      - db
  frontend:
    image: ghcr.io/merpw/lets-play-frontend:${REVISION-main}
    platform: linux/amd64
    build:
      context: frontend
  db:
    image: mongo
    volumes:
      - lets-play-db:/data/db
  swagger-ui:
    image: swaggerapi/swagger-ui
    environment:
      URLS: "[
      {name:'Users',url:'/api/api-docs-users'},
      {name:'Products',url:'/api/api-docs-products'},
      {name:'Media',url:'/api/api-docs-media'},
      {name:'Orders',url:'/api/api-docs-orders'}
      ]"
      BASE_URL: /api/docs
volumes:
  lets-play-db:
  lets-play-media:

