services:
  api:
    build: .
    environment:
      - MONGO_HOST=db
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - lets-play-db:/data/db
volumes:
  lets-play-db:

