services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - products
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/ssl:/etc/ssl
  users:
    image: ghcr.io/merpw/lets-play-users-service:${REVISION-main}
    build:
      context: backend
      args:
        - SERVICE_NAME=users
    environment:
      - MONGO_HOST=db
    depends_on:
      - db
  products:
    image: ghcr.io/merpw/lets-play-products-service:${REVISION-main}
    build:
      context: backend
      args:
        - SERVICE_NAME=products
    environment:
      - MONGO_HOST=db
    depends_on:
      - db
  media:
    image: ghcr.io/merpw/lets-play-media-service:${REVISION-main}
    build:
      context: backend
      args:
        - SERVICE_NAME=media
    environment:
      - MEDIA_STORAGE_DIR=/app/media
    volumes:
      - lets-play-media:/app/media
  frontend:
    image: ghcr.io/merpw/lets-play-frontend:${REVISION-main}
    build:
      context: frontend
  db:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - lets-play-db:/data/db
volumes:
  lets-play-db:
  lets-play-media:

