name: Build and Push Docker image
description: Build and push Docker image of the affected service to GitHub Container Registry

inputs:
  token:
    description: "GitHub token"
    required: true
  registry:
    description: "Container registry"
    default: ghcr.io
    required: true
  context:
    description: "Context path"
    default: .
    required: true
  build-args:
    description: "Build arguments"
    required: false
  image-name:
    description: "Image name"
    required: true

runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ${{ inputs.registry }}
        username: ${{ github.actor }}
        password: ${{ inputs.token }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ inputs.registry }}/${{ github.repository }}-${{ inputs.image-name }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      uses: docker/build-push-action@v4
      with:
        context: ${{ inputs.context }}
        build-args: ${{ inputs.build-args }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha,scope=global
        cache-to: type=gha,mode=max,scope=global
