spring:
  data:
    mongodb:
      host: ${MONGO_HOST:localhost}

security:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:}
  jwt:
    secret: ${JWT_SECRET:UnsafeSecret}
  password:
    salt: ${PASSWORD_SALT:}

initial:
  admin:
    enabled: ${ADMIN_ENABLED:true}
    name: ${ADMIN_USERNAME:admin}
    password: ${ADMIN_PASSWORD:AdminAdmin}
    email: ${ADMIN_EMAIL:admin@localhost}