spring:
  data:
    mongodb:
      host: ${MONGO_HOST:localhost}

jwt:
  private_key: classpath:jwt.key
  public_key: classpath:jwt.key.pub

initial:
  admin:
    enabled: ${ADMIN_ENABLED:true}
    name: ${ADMIN_USERNAME:admin}
    password: ${ADMIN_PASSWORD:admin}
    email: ${ADMIN_EMAIL:admin@localhost}