spring:
  data:
    mongodb:
      host: ${MONGO_HOST:localhost}

security:
  jwt:
    secret: ${JWT_SECRET:UnsafeSecret}

initial:
  admin:
    enabled: ${ADMIN_ENABLED:true}
    name: ${ADMIN_USERNAME:admin}
    password: ${ADMIN_PASSWORD:AdminAdmin}
    email: ${ADMIN_EMAIL:admin@localhost}

docs:
  api-url: ${DOCS_API_URL:/}