services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/ssl:/etc/ssl
  api:
    image: ghcr.io/merpw/lets-play
    environment:
      - MONGO_HOST=db
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - PASSWORD_SALT=${PASSWORD_SALT}
    depends_on:
      - db
  db:
    image: mongo
    volumes:
      - lets-play-db:/data/db
volumes:
  lets-play-db:

