name: Test and Build Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-and-build:
    strategy:
      matrix:
        services: [ users, products ]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/test
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          service-name: ${{ matrix.services }}
      - uses: ./.github/actions/docker
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          service-name: ${{ matrix.services }}
