name: On Pull Request

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

jobs:
  build-backend:
    uses: ./.github/workflows/backend-docker.yml

  build-frontend:
    uses: ./.github/workflows/frontend-docker.yml

  build-nginx:
    uses: ./.github/workflows/nginx-docker.yml